MANUAL_READING_PASSAGES = {
    2016: {
        "a": """Text 1: Wenige Freunde fürs Leben

Freunde finden war nie einfacher: Mit 350 Menschen ist jeder Facebook-Nutzer im Durchschnitt verbunden, junge Erwachsene haben sogar 649 Freunde. Goldene Zeiten für die Freundschaft könnte man meinen. Doch eine Analyse von US-Forschern kommt zu anderen Ergebnissen: Obwohl die Kontakte in sozialen Medien zunehmen, bleibt die Anzahl enger Vertrauter erstaunlich gering und sinkt im Laufe des Lebens sogar noch.

Für die Studie, die im Fachmagazin Plos One erschienen ist, befragten Forscher um Brian Gillespie von der Sonoma State University 25.185 zufällig ausgewählte Besucher einer Nachrichtenseite zu ihrem Freundeskreis. Da jeder etwas anderes unter dem Begriff Freundschaft versteht, stellten die Soziologen spezifischere Fragen: Von wie vielen Ihrer Freunde würden Sie erwarten, dass sie mit Ihnen etwas an Ihrem Geburtstag unternehmen? Wie viele könnten Sie mitten in der Nacht bei einem persönlichen Problem anrufen? Mit wie vielen sprechen Sie über das eigene Sexualleben?

Die meisten Befragten rechneten damit, dass zwischen fünf und zehn Personen zur Geburtstagsparty erscheinen würden. Für den nächtlichen Notfall kämen etwa fünf bis sieben Telefonnummern infrage. Und im Durchschnitt würden sie mit drei bis sieben Personen über Intimes sprechen.

Die Wissenschaftler durchleuchteten die Freundschaftsnetzwerke zudem nach Geschlecht und sexueller Orientierung. So bestand die Vermutung, dass schwule Männer und lesbische Frauen mehr Freundschaften pflegen als Heterosexuelle. Da sie häufig einem homophoben und ablehnenden Umfeld ausgesetzt seien, brauchten sie zum Ausgleich ein größeres soziales Netz, vermutete man. Zudem seien Schwule mit mehr Frauen befreundet als Heterosexuelle.

Die Studie räumt mit diesen Vorstellungen auf. Unterschiede zwischen sexuell unterschiedlich orientierten Gruppen „sind allgemein klein oder nicht vorhanden“, schreiben die Soziologen. Auch die Anzahl enger Freunde hänge nicht von der sexuellen Orientierung ab. Allerdings weisen die Forscher darauf hin, dass ihre Stichprobe nicht repräsentativ und die Aussage ihrer Arbeit daher begrenzt ist. Dazu kommt, dass an Netz-Umfragen überdurchschnittlich viele Menschen aus gebildeten und einkommensstarken Schichten teilnehmen.

Einig sind sich Wissenschaftler darin, dass das Alter für Freundschaften eine große Rolle spielt. „In der Jugend schließt man immer mehr Freundschaften, doch schon im frühen Erwachsenenalter sinkt die Zahl wieder“, sagt der Psychologe Franz Neyer von der Universität Jena. Bei der Auswertung mehrerer Studien mit insgesamt 178.000 Teilnehmern konnte ein Team um Neyer zeigen, dass 25-Jährige die meisten Freundschaften pflegen - danach geht die Zahl stetig zurück.

„An der Zahl richtig guter Freunde, die man im Leben trifft, haben auch soziale Medien nichts geändert“, sagt Neyer. Für die Lebenszufriedenheit sei die Anzahl der Freunde ohnehin ohne Belang, so der Psychologe. „Dafür ist allein die Qualität der Freundschaften entscheidend.“

(415 Wörter, aus Süddeutsche Zeitung online, leicht gekürzt)""",
        "b": """Text 2

Die 160.000 Flüchtlinge sollen über die umstrittene Quote so verteilt werden: 26,2% in Deutschland, 20,0% in Frankreich, 12,4% in Spanien, 7,7% in Polen, 6,0% in Holland, 3,9% in Rumänien, 3,7% in Schweden, 3,0% in Österreich, 1,3% in der Slowakei und 0,3% in Estland.

507 Millionen Einwohner zählen die 28 Mitgliedstaaten der EU. Gemessen an seiner Bevölkerungszahl müsste Deutschland eigentlich 15,8 Prozent der Flüchtlinge aufnehmen. Tatsächlich sind es aber 26,2 Prozent. Der Grund: Großbritannien, Dänemark und Irland gehören nicht zum europäischen Asylsystem. Bei den verbliebenen EU-25 geht die Bevölkerungszahl nur zu 40 Prozent in die Quotenberechnung ein, mit weiteren 40% wird die Wirtschaftskraft gewichtet. Die restlichen Kriterien sind die Arbeitslosenrate und die Zahl der bereits aufgenommenen Flüchtlinge pro eine Million Einwohner zwischen 2010 und 2014.

Noch ist zweifelhaft, ob die Quote überhaupt eingeführt und unbegrenzt angewendet werden soll. Denn in Osteuropa tönt es unisono: „Quote? - Nein, danke.“ Trotz unterschiedlicher Parteizugehörigkeiten und vorheriger Differenzen zeigen sich die Regierungen verblüffend einig.

Deutsche Politiker machen gern die Rechnung auf, dass die EU mit ihren 507 Millionen Einwohnern doch leicht eine Million Flüchtlinge aufnehmen könnte. „Natürlich gibt es Grenzen. Ich sehe aber nicht, dass die derzeit in irgendeiner Weise erreicht sind“, sagt Rainer Wend (SPD), Präsident der Europäischen Bewegung Deutschland (EBD).

Andere Länder bekennen sich in der Asylpolitik offener zu eigenen Interessen als Deutschland. Nicht nur der verständliche Fluchtimpuls der Menschen aus Kriegs- und Krisenzonen ist für sie ein Maßstab, sondern auch die Aufnahmebereitschaft der eigenen Bevölkerung. Kann Deutschland vielleicht auch deshalb mehr Flüchtlinge aufnehmen als der direkte Nachbar Frankreich, weil hierzulande keine Rechtspartei die Stimmung gegen Einwanderer schürt?

In Brüssel ist der Wille zur gerechten Lastenverteilung vorhanden. Die EU-Außenpolitikbeauftragte, Federica Mogherini, betont: „Diese Leute kommen nach Europa, nicht in diesen oder jenen Mitgliedsstaat.“ Deshalb sei die EU als Ganzes gefordert. Aber ihr Chef, Kommissionspräsident Jean-Claude Juncker, muss eingestehen: „Es fehlt an Europa in dieser Europäischen Union. Und es fehlt an Union in dieser Europäischen Union.“ EBD-Präsident Wend bedauert: „Die gemeinsame EU-Innen- und Außenpolitik bleibt ein weißes Blatt Papier.“

Zudem ist eine Neuverteilung der Flüchtlinge mit Kosten verbunden. 6.000 Euro zahlt Brüssel für jeden Umsetzungsfall an das Zielland. „Wir wollen jetzt mal wissen, was mit dem Geld bisher gemacht wurde und ob man das stärker kontrollieren muss“, kündigt Ausschussvorsitzende Ingeborg Gräßle (CDU) an. Sie plädiert auch dafür, Staaten, die sich der europäischen Solidarität entziehen, nicht mehr mit Zahlungen aus dem EU-Strukturfonds zu bedenken.

(415 Wörter, aus Focus, Nr. 38/2015, bearbeitet)""",
    },
    2017: {
        "a": """Text 1: EU verschärft Datenschutzstandards im Internet

Vor vier Jahren hat die damalige Justizkommissarin Viviane Reding einheitliche neue Datenschutzregeln für die Europäische Union vorgeschlagen. Nun haben Unterhändler von Europaparlament und Ministerrat, dem Gremium der EU-Mitgliedstaaten, die Reform des Datenschutzes auf die Zielgerade gebracht. Die europäischen Verbraucher bekommen damit - vor allem im Internet - mehr Kontrolle über ihre persönlichen Daten. Internetkonzerne wie Google oder Facebook müssen die Zustimmung der Nutzer ausdrücklich einholen, wenn sie deren Daten nutzen wollen. Die Nutzer erhalten außerdem das Recht, ihre Daten soweit wie möglich löschen zu lassen und Daten von einem Anbieter zu einem anderen mitzunehmen.

Auf einen Kompromiss einigten sich die Unterhändler von Europaparlament und Ministerrat auch beim Mindestalter für die Nutzung sozialer Netzwerke von Facebook über Twitter bis Instagram. Das Europaparlament hatte zuvor ein Mindestalter von 13 Jahren gefordert. Nun sollen die EU-Mitgliedstaaten das Mindestalter individuell festlegen können. Sie müssen aber die Spanne zwischen 13 und 16 Jahren einhalten.

Die Unternehmen müssen nach der Einigung ihre Angebote grundsätzlich derart ausgestalten, dass sie dafür möglichst wenige Daten erheben müssen. Wenn sie gegen die neuen Regeln verstoßen, drohen ihnen hohe Strafen. Zwar konnte sich das Europaparlament mit seiner Forderung nach Strafen von bis zu 5 Prozent des weltweiten Jahresumsatzes nicht durchsetzen. In dem Kompromiss ist aber immer noch von 4 Prozent die Rede. Bei Unternehmen wie Facebook oder Google geht es dabei um Milliardensummen. Andererseits profitieren die Unternehmen davon, dass nun in der EU überall dasselbe Datenschutzniveau gilt. Bisher ist das nur eingeschränkt der Fall. Die bisherigen Regeln stammen aus dem Jahr 1995, die von jedem EU-Land anders umgesetzt worden sind. Dadurch ist ein Flickenteppich an Vorschriften entstanden, was die Kosten für in allen 28 EU-Staaten tätige Unternehmen in die Höhe trieb. Die Europäische Kommission hat das Einsparpotential auf bis zu 2,3 Milliarden Euro im Jahr beziffert. Die Zahl ist allerdings umstritten.

Der CDU-Abgeordnete Axel Voss sagte: „Vorbehaltlich des weiteren Verfahrens wird es künftig ein Regelwerk für den europäischen Datenschutz geben anstatt eines Flickenteppichs, der sich aus 28 Datenschutzbestimmungen zusammensetzt.“ Zugleich kritisierte er, die Regelung werde den digitalen Herausforderungen nicht gerecht: „Wir müssen aufpassen, dass dies am Ende nicht ein Hemmschuh für die europäische Industrie und Forschung wird.“ Über die massenhafte Analyse von persönlichen Daten („Big Data“) war in den vergangenen Wochen ein heftiger Streit entbrannt. Vor allem die Bundesregierung, die sich jahrelang eher für ein besonders hohes Datenschutzniveau eingesetzt hatte, drang am Ende auf Ausnahmeregeln, um das Potential von „Big Data“ ausschöpfen zu können.

(406 Wörter, aus: http://www.faz.net, stark gekürzt)""",
        "b": """Text 2: Wir brauchen Digitalkunde ab der ersten Klasse

In 20 Jahren wird etwa jeder zweite Arbeitsplatz der Digitalisierung zum Opfer gefallen sein, prognostizieren die Forscher Michael Osborne und Carl Frey von der Universität Oxford. Wegfallen wird, was heute die Breite der Beschäftigungsbasis darstellt, wie zum Beispiel Büro- und Assistentätigkeiten oder die produzierenden Berufe in Fabriken. Allerdings wäre es falsch, jetzt anzunehmen, es träfe nur die durchschnittlich qualifizierten und mäßig bezahlten Berufe. Computer können zum Teil schon heute bessere Krebsbehandlungspläne und Diagnosen formulieren als hochspezialisierte Fachärzte, sie können Texte verstehen und Schlüsse ziehen und zunehmend gut in natürlicher Sprache kommunizieren. Damit werden Berufsgruppen getroffen, die über Jahrzehnte als Garanten für gute Ausbildung, Berufschancen und Verdienstmöglichkeiten galten.

20 Jahre erscheinen noch relativ weit entfernt. Aber für die Bildungsfrage ist das praktisch „jetzt“, denn Kinder, die heute eingeschult werden, werden in etwa 20 Jahren in den Arbeitsmarkt eintreten. Wir müssen also über Bildung reden, und zwar schnell. Deshalb vertritt Stephan Noller als Beirat des Bundeswirtschaftsministeriums die Forderung, das Fach „Digitalkunde“ verbindlich ab der ersten Klasse einzuführen. Diese Forderung wird umso drängender, je mehr man sich mit dem aktuellen Schulsystem in Deutschland auseinandersetzt. Die Vermittlung von digitalen Kenntnissen ist in den letzten Jahren eher noch mehr verkümmert, als dass sie strategisch ausgebaut worden wäre. Heutige Informatik-AGs sind oft nur Einführungskurse in die Text- und Tabellenkalkulation mit Office-Programmen. Von einer flächendeckenden Vermittlung von Kenntnissen für die Welt in 20 Jahren ist hingegen weit und breit nichts zu sehen.

Großbritannien hat dagegen im Eilverfahren ein verpflichtendes Informatik-Curriculum ab dem ersten Schuljahr eingeführt, und zwar landesweit. Andere Länder bereiten ähnliche Schritte vor. In Deutschland werden an vielen Schulen weitgehende Handyverbote erteilt und das WLAN funktioniert auch nicht. Wenn uns an der Zukunft unserer Kinder gelegen ist, müssten die Eltern eigentlich längst Sturm laufen - von den Vertretern der Wirtschaft mal ganz zu schweigen. Es geht um mehr als nur die Qualifikation für den Arbeitsmarkt. Denn die Digitalisierung bringt nicht nur neue Maschinen und andere Prozesse in den Arbeitsalltag, vielmehr wird sie unseren gesamten Alltag betreffen. In 20 Jahren werden unsere Häuser voller Sensoren sein, ebenso die Autos und der öffentliche Raum.

So soll die Schule dabei helfen, unsere Kinder zu digital souveränen Bürgern zu machen. Mit Tabellenkalkulation und aufgeklärter Medienrezeption ist es da nicht getan. Möglichkeit viele heutige Erstklässler sollten in der Tiefe verstehen können, was es bedeutet, von einer digitalen Sphäre umgeben zu sein. Dafür reicht es nicht, weiter darauf zu setzen, dass die Kinder sich das „eh irgendwie draufschaffen“. Wir brauchen Pädagogen, Material und Zeit, um Kinder auf diese neue Gesellschaft und die völlig neuen beruflichen Herausforderungen vorzubereiten.

(433 Wörter, aus: http://www.zeit.de, stark gekürzt.)""",
    },
    2018: {
        "a": """Text 1

Wer den Namen Angela Merkel googelt, bekommt bei Google gleich auf der ersten Ergebnisseite grundsätzliche Infos. „Angela Dorothea Merkel ist eine deutsche Politikerin und seit dem 22. November 2005 amtierende Bundeskanzlerin“, heißt es in einer Infobox, die direkt neben der Liste mit den Suchergebnissen den Wikipedia-Eintrag zu Merkel zitiert. Man erfährt unter anderem, wie groß die Kanzlerin ist und dass ihr Ehemann Joachim Sauer heißt.

Ähnliche Infoboxen sollen ab der zweiten Augusthälfte bei Suchen nach Tausenden deutschen Politikern auftauchen, auch bei viel weniger bekannten - und die Infoboxen sollen auch gleich klarmachen, für was der jeweilige Politiker steht. Google bietet dieses Jahr allen für die Bundestagswahl zugelassenen Kandidaten die Chance, diese Boxen teilweise selbst zu betexten.

Im Anschluss an - je nach Informationsbasis mehr oder weniger ausführliche - Fakten zur Person wie etwa die Körpergröße oder die Parteienzugehörigkeit werden die Boxen ausnahmsweise Platz fürs Selbstmarketing bieten: In maximal 500 Zeichen sollen die Kandidaten ihren politischen Grundsatz erklären dürfen und dann noch drei Prioritäten, ihre wichtigsten Themen im Wahlkampf. Dabei sind sie allerdings auf jeweils 140 Zeichen beschränkt, also auf die Länge eines Twitter-Postings.

Das Angebot ist freiwillig. Von Google heißt es, das Unternehmen bemühe sich möglichst alle der geschätzt 4.500 Kandidaten zu erreichen und um Eingaben für die Box zu bitten. Beim Inhalt seien die Kandidaten frei, heißt es, solange ihre Botschaften nicht zum Beispiel volksverhetzend seien.

Für die Kandidaten ist das Angebot verlockend: Wenn es auf den Wahltag zugeht, suchen erfahrungsgemäß viele Menschen online nach Informationen zu den Kandidaten aus ihrem Wahlkreis (wenn sie überhaupt wissen, welcher ihr Wahlkreis ist - eine Information, die Google ab Ende August ebenfalls mit einem neuen Online-Angebot liefern will). Weil die Boxen wie beim Beispiel Merkel ohne einen weiteren Klick sichtbar sind, sobald man eine Google-Suche durchgeführt hat, sind die Informationen kaum zu übersehen.

Googles Betexte-deine-Box-Service bietet den Politikern nun die Chance, ungefiltert für sich und ihre Positionen zu werben: Auf der ersten Suchergebnisseite zu ihrem Namen steht so, was sie dort stehen haben wollen - und womöglich fällt manches unliebsame Ergebnis, was sonst direkt bei ihrem Namen auftaucht, den Nutzern so weniger ins Auge.

Für den Fall, dass sich die Prioritäten eines Kandidaten in den kommenden Wochen mal verschieben, lässt Google die Politiker ihre Sprüche zwischendurch auch überarbeiten. Auch ein Verlinken der eigenen Social-Media-Accounts in der Box soll möglich sein, nicht aber das Einbauen von Fremdlinks. Schon am Tag nach der Wahl, die am 24. September stattfindet, sollen die Boxen wieder offline gehen. Doch für internetaffine Kandidaten bleibt die Chance, sich schon auf den nächsten Wahlkampf vorzubereiten.

(450 Wörter, aus Süddeutsche.de, stark gekürzt)""",
        "b": """Text 2: Kakerlaken-Roboter als Lebensretter

„Insekten sind die erfolgreichsten Tiere unserer Erde“, sagt Robert Full, Professor der Systembiologie an der Universität Berkeley. Denn sie dringen nahezu überall ein - wir sollten sie als Inspiration betrachten. Und wer es schon einmal mit Kakerlaken zu tun hatte, weiß: Die Viecher können sich ganz flach machen und kommen einfach durch alle Ritzen. Genau das wollten sich Forscher der kalifornischen Universität Berkeley zunutze machen. Sie haben einen handflächengroßen Roboter entwickelt, der dem Krabbeltier ähnelt und Menschen das Leben retten soll.

Das Ergebnis dieser Inspiration heißt CRAM, der einige Eigenschaften echter Kakerlaken in sich trägt. Bislang gibt es nur einen Prototyp. Doch CRAM, so die Idee, könnte bei der Suche Verschütteter bereits dann loslegen, wenn Suchhunden oder Menschen das noch längst nicht möglich ist.

Im Fall von Erdbeben müssen die Helfer zuallererst wissen, ob ein Schuttberg stabil und einigermaßen sicher ist. Erst dann ist die Suche nach Verschütteten möglich. Aber die meisten gängigen Roboter können in solches Geröll nicht eindringen. Kakerlaken aber schon. Ein Grund dafür liegt in ihren anatomischen Fähigkeiten: Die Insekten können ihre Beinstellung bei Bedarf komplett zur Seite ausrichten und sogar auf den Schienbeinen weiter krabbeln und so auch besonders enge Öffnungen bezwingen. Außerdem sind die Tiere äußerst druckbeständig. „Sie können das 900-fache ihres eigenen Gewichts auf ihrem Körper überstehen“, erklärt Studienleiter Kaushik Jayaram, der den Schabenroboter entwickelt hat.

Und auch die künstliche Kakerlake kann ihre Beine zu den Seiten hin ausrichten und hält äußerst starken Quetschungen stand - dank eines sehr robusten Kunststoffpanzers. Durch diese Fähigkeiten ist CRAM auch dann noch in der Lage zu krabbeln, wenn er auf die Hälfte seiner eigentlichen Höhe gedrückt wird.

Ist ein potenzieller Durchgang einmal besonders flach, bewegen sich echte Kakerlaken anstatt auf ihren Füßen auf den Schienbeinen fort. Auch das Roboterinsekt aus Berkeley verfügt über Beine, deren Füße bei Bedarf zurückgeklappt werden können.

Kaushik Jayaram und Robert Full, die Köpfe hinter CRAM, haben „Amerikanische Großschaben“ durch exakt vermessene Gänge laufen lassen. Darin mussten die Tiere durch Ritzen kriechen, die 6,1 mm oder auch nur 3,2 mm hoch waren. Bei letzterem Spalt reduzierten die Tiere ihre ursprüngliche Höhe von gut 12 mm auf ein Viertel.

Auch die Robotervariante der Krabbeltiere beherrscht dank seines ausgetüftelten Exoskeletts dieses Kunststück. Der eigentlich 75 mm hohe CRAM kann auch mit 35 mm Körperhöhe noch nahezu uneingeschränkt weiterlaufen. Deshalb auch sein Name. CRAM steht für „compressible robot with articulated mechanisms“. Auch wenn das umständlich klingt: Krabbeln kann CRAM richtig gut.

Die Forscher aus Berkeley sind nicht die ersten, die von den Fähigkeiten der Kakerlaken fasziniert sind. Kollegen der North Carolina State University haben eine Fernsteuerung entwickelt, die echten Kakerlaken auf den Rücken geklebt wird. So wollen sie die Tiere nutzen, um Verschüttete aufzuspüren.

(449 Wörter, aus Ingenieur.de, leicht gekürzt)""",
    },
    2023: {
        "a": """Text 1: Wenn Algorithmen Emotionen entschlüsseln

Der Angestellte Milenko Saponja versucht, „glücklich“ zu sprechen, doch die Anzeige seines Smartphones zeigt ihm ein Symbol für „neutral“. Auf dem Handy läuft eine spezielle App von Audeering, einer Softwarefirma für Audioanalyse in Gilching bei München. Firmenchef Björn Schuller erklärt: „Das Problem ist, dass das System mit echten Emotionen trainiert wurde, deshalb erkennt es vorgetäuschte Emotionen sofort.“ An diesem Tag sollen die Firmenangestellten die App vorstellen, wofür sie ihre Stimmen verstellen, um bestimmte Emotionen auszudrücken. Gefühle und Persönlichkeitsmerkmale beeinflussen unsere Stimme - und diese verrät, wie wir uns fühlen und letztlich offenbart sie, wer wir sind.

Die Technik zur Analyse kann schon bald Teil des Alltags werden. Denn es kommen aktuell zwei Faktoren zusammen: Erstens die Computertechnik des maschinellen Lernens mit ihrem Talent, verborgene Muster zu erkennen. Zweitens die Daten, weil heute immer mehr Menschen vermittels ihrer Digitalgeräte miteinander sprechen. Dadurch entstehen riesige Datenmengen.

Shrikanth Narayanan von der University of California hat vor ein paar Jahren eine für die Beteiligten emotional belastende Situation untersucht, indem er aufzeichnete, wie Eheleute bei Paartherapien miteinander sprechen. Der Computer hat daraufhin lediglich den Klang der Stimmen analysiert. Später erhielt der Algorithmus Informationen darüber, welches Paar verheiratet geblieben ist - und welches nicht. Bald darauf war das System in vier von fünf Fällen in der Lage, die korrekte Prognose anzugeben, ob es bei einem Paar nach dem Therapieende zur Scheidung kam. Das System lieferte damit eine bessere Prognose als die TherapeutInnen.

Die ersten Systeme zur Gefühlserkennung sind schon aus den Laboren gekommen. In Deutschland allerdings muss man die Menschen vor dem Einsatz einer Analyse informieren, doch kaum jemand weiß genau, was mit Sprachaufnahmen auf den Servern von großen US-amerikanischen Firmen passiert. Die sammeln am fleißigsten. Amazon hat schon ein Patent darauf angemeldet, Emotionen und Krankheiten der Nutzer aus der Stimme zu erkennen.

Schuller von Audeering erzählt, dass er vor 18 Jahren mit Projekten für junge Autisten begann, um Eltern die Erkennung der Gefühle ihrer autistischen Kinder zu erleichtern. Beispielsweise lernen autistische Kinder mit Hilfe spezieller Spiele und niedlicher Roboter, ihre Emotionen auszudrücken. Technik für etwas Gutes!

Eines darf man nicht vergessen: Das größte Interesse an dieser Technologie zeigen Firmen, die sich für den Menschen nicht als Patienten, Probanden oder Klienten interessieren, sondern als Konsumenten. Die Kunden von Audeering sind zum Beispiel Beratungsinstitute, die an der Stimme die Meinung der Leute zu einem Produkt erkennen wollen.

Auch an der Analyse von Stimmdaten aus dem Internet gibt es ein sehr großes Interesse, wenn beispielsweise Personen auf Youtube über ein Produkt sprechen. Und für das Verkaufen in der Zukunft ist es wichtig, den Kunden im richtigen Moment anzusprechen. So schützt Amazons Gefühlserkennungs-Patent eine Methode, um KundInnen je nach Stimmungslage passende Produkte vorzuschlagen. Derzeit wird auch an der Umkehrung gearbeitet: Maschinen, die uns durch unmerkliche Details ihrer synthetischen Stimmen die Freude, Anteilnahme oder Aufrichtigkeit vortäuschen können, das Gefühl geben, dass sie uns wirklich verstehen.""",
        "b": """Text 2: Andere Sprache, andere Moral?

Stellen Sie sich vor, ein Zug rast auf eine Gruppe von fünf Männern zu. Er wird sie töten, doch gibt eine letzte Möglichkeit, die Männer zu retten: Man stößt einen anderen Mann von einer Brücke auf die Gleise, damit sein Körper den Zug abbremst. Würden Sie das tun? Einer Studie zufolge hängt die Antwort nicht nur von den Moralvorstellungen eines Menschen ab, sondern auch von der Sprache, in der man dieses Dilemma beurteilen muss. Denn es ist nicht dasselbe, ob jemand in seiner Muttersprache über das Leben der Personen auf dem Gleis entscheiden muss oder in einer Fremdsprache. In einer Fremdsprache ist die Tendenz bei vielen Leuten größer, den Mann von der Brücke hinunterzustoßen.

Ob Fremdsprache, Dialekt oder Umgangssprache: Wie wir sprechen, macht uns auch zu dem, was wir sind und wie uns andere sehen. Täglich spielen wir vermittels der Sprache verschiedene Rollen: Wir wollen jemand anderes sein oder werden es ganz automatisch, je nachdem mit wem wir sprechen. Bei anderen findet die Verwandlung unbewusst statt, ohne dass sie es bemerken. Der eine spricht seinen Heimatdialekt, wenn er zu Hause bei der Familie ist, der andere fühlt sich auf Französisch intellektueller. Mehrsprachige Menschen haben oft das Gefühl, teilweise zu einer anderen Person zu werden, wenn sie die Sprache wechseln.

So lernt man mit einer fremden Sprache neue Arten, sich auszudrücken. Manchmal ändert man sogar seine Körpersprache, Mimik sowie Stimme und fühlt sich fast wie eine andere Person. „Sprachen können wie Masken sein“, befindet Prof. Dewaele, Sprachwissenschaftler an der University of London. Menschen empfinden in einer Fremdsprache mehr Freiheit, Dinge zu tun, die ihnen sonst nicht erlaubt sind. Warum ist das so?

Antwort auf diese Frage weiß Albert Costa, Psychologe an der Universität Pompeu Fabra in Spanien und einer der Wissenschaftler, die sich das am Anfang beschriebene Experiment ausgedacht haben. Das Zug-Dilemma ist ein berühmtes Gedankenexperiment. Aber die Idee, die TeilnehmerInnen in einer Fremdsprache damit zu konfrontieren, hatte vor ihm und seinen Kollegen noch niemand gehabt.

Bei dem Experiment lehnten es durchschnittlich 80 Prozent der Befragten ab, den Mann vor den Zug zu stoßen. „Es fühlt sich einfach falsch an“, so die emotionale Reaktion. Aber es gibt auch utilitaristische Gründe, den Mann von der Brücke zu stoßen, da man so fünf andere Menschen retten kann. Eine „richtige“ Antwort in diesem Dilemma gibt es nicht; wie jemand entscheidet, hängt scheinbar von dessen Moralvorstellungen ab.

Doch waren diese überraschend flexibel, wie Costa feststellte, als er SpanierInnen auf Englisch fragte: Plötzlich wollten dreimal mehr Personen den Mann von der Brücke stoßen. Die TeilnehmerInnen entschieden öfter utilitaristisch und hatten weniger Hemmungen, den Mann zu opfern. Sie handelten nach dem Prinzip: Fünf Leben zu retten ist besser als eines. Die emotionale Reaktion der TeilnehmerInnen auf das Dilemma war nicht dieselbe wie in ihrer Muttersprache.

Wissenschaftler erklären, dass die Muttersprache einen tieferen emotionalen Resonanzraum in uns anlegt, als Fremdsprachen das normalerweise können. In einer Fremdsprache denken, sprechen und handeln wir mit größerer emotionaler Distanz und weniger verzagt, wodurch die emotionale Bürde der Moral weniger schwer wiegt.

Nach Costa hat es mit dem Kontext zu tun, in dem Menschen eine Fremdsprache lernen. Seine Muttersprache erwirbt man im emotionalen Umfeld der Familie, weshalb sie eng mit der Gefühlswelt verknüpft ist. Eine Fremdsprache hingegen lernen viele unter komplett anderen Bedingungen im Klassenzimmer.""",
    },
    2025: {
        "a": """Text 1: KI hilft bei der Entwicklung von Medikamenten

Mehr als 13 Jahre dauert es meistens von der Idee für eine neue Behandlung bis zum zugelassenen Medikament - länger als von der Einschulung bis zum Abitur. Dieser Weg besteht aus vielen Schritten: Die ersten finden im Labor statt, anschließend folgen Tests mit Zellkulturen und mit Tieren, um alle neuen Wirkstoffe auszuschließen, die schädlich für den Menschen sein könnten. Wenn ein Wirkstoff alle Labortests erfolgreich abgeschlossen hat, kann er unter streng kontrollierten Bedingungen an Menschen erprobt werden. Das geschieht in klinischen Studien, erst mit Gesunden, später mit Patienten. Dieser umfassende Schritt der Erprobung des Wirkstoffes an Menschen gliedert sich grundsätzlich in drei Phasen, nämlich Phase I - Erprobung mit wenigen Gesunden, Phase II - Erprobung mit wenigen Kranken und Phase III - Erprobung mit vielen Kranken. Jede dieser Phasen dauert meistens mindestens ein Jahr, meist länger. Erst wenn eine Substanz all diese Schritte erfolgreich durchlaufen hat, wenn die Wirksamkeit und die Sicherheit nachgewiesen sind, kann die Zulassung erfolgen. Am Ende dieses Prozesses ist ein neues Medikament verfügbar.

Arzneimittelentwicklung ist ein aufwändiges, kostenintensives und wirtschaftlich riskantes Unterfangen, denn von 5.000 bis 10.000 Substanzen sind schon nach 5 Jahren im Schnitt nur ungefähr 9 aussichtsreich - und nur eine einzige wird schließlich zugelassen. Um Arzneimittel effizienter zu entwickeln und damit rascher zu den PatientInnen zu bringen, setzen Pharmaunternehmen auf innovative Technologien. Intensiv wird derzeit an modernen Softwarelösungen gearbeitet, die unter den Begriff der künstlichen Intelligenz (KI) fallen. Um vielversprechende Ideen für Arzneien gezielt zu identifizieren, können KI-Modelle bereits jetzt in der Forschung eingesetzt werden. Methoden wie maschinelles Lernen helfen dabei, Moleküle, also chemische Bausteine, zu finden, die mit den menschlichen Zellen wirksam interagieren.

Dabei helfen KI-Modelle, neue Moleküle virtuell auf ihre Eignung als Arzneistoff zu untersuchen und notwendige chemische Anpassungen auf molekularer Ebene am Bildschirm darzustellen. Ein Beispiel: Mit Hilfe von Hochleistungsrechnern und modernster Software ist es einem Pharmaunternehmen bereits gelungen, ein Arzneimittel von der Molekülenwicklung für eine orale statt einer intravenösen Darreichungsform zu planen. Auf diese Weise sind Patienten nicht gezwungen, für jede Injektion ins Krankenhaus zu fahren, sondern sie können das Medikament bequem zu Hause durch den Mund einnehmen.

In der Arzneimittelentwicklung ist es besonders schwierig, den dreidimensionalen Aufbau von Proteinen vorauszusagen, d. h. die genaue Position der einzelnen Atome. Proteine sind große Moleküle mit mehreren Strukturebenen, deren komplexer Aufbau für ihre Wirksamkeit als Arzneimittel entscheidend ist. Mit Methoden der künstlichen Intelligenz sind mittlerweile bedeutende Fortschritte erzielt worden, wodurch der Aufbau solcher Proteine besser vorhergesagt werden kann. Wirkstoffe für die Arzneimittel können somit passgenauer, d. h. schneller und somit preiswerter entwickelt werden.

Zu den folgenreichsten Entscheidungen in der Arzneimittelentwicklung gehört das „Aussortieren“ von Substanzen, die man nicht weiterverfolgen möchte, weil sie voraussichtlich wenig wirksam sind oder schwerwiegende Nebenwirkungen haben. KI kann dabei helfen, die physikalischen Eigenschaften, die Bioaktivität, d. h. den Einfluss einer Substanz auf den lebenden Organismus, und die Toxizität, das Maß für die schädigende Wirkung eines möglichen Wirkstoffes, vorauszusagen und negative Auswirkungen auszuschließen.""",
        "b": """Text 2: Die Germanen

Die Germanen als einheitliches Volk hat es nie gegeben. Vielmehr ist die Bezeichnung ein Oberbegriff für zahlreiche Stämme, die im Gebiet zwischen Rhein, Donau und Weichsel lebten. Diese Stämme bildeten keinen gemeinsamen Staat und hatten keine gemeinsame Identität, ganz im Gegenteil, regelmäßig bekämpften sie sich untereinander. Zur Zeit der Hochkulturen der Griechen und Römer wusste man im Mittelmeerraum nur wenig von den Völkern des Nordens. Lange Zeit wurden sie unter dem Begriff „Barbaren“ zusammengefasst - also Menschen, die keine griechisch-römische Bildung genossen hatten. Erst um 80 vor Christus taucht der Begriff „Germanen“ beim griechischen Geschichtsschreiber Poseidonios auf. Den Begriff verbreitet hat Gaius Julius Cäsar (100 bis 44 vor Christus) in seinem Werk „De bello gallico“. Die Bezeichnung „Germanen“ stammt demnach nicht von den Menschen, die damit erfasst wurden, denn diese fanden ihre Identität in ihren Stammesgemeinschaften.

Die Siedlungs- und Gesellschaftsstruktur der verschiedenen Germanenstämme war im Wesentlichen gleich: Die Familie bildete den Kern der germanischen Gesellschaft, ihr gegenüber waren alle Mitglieder zu Treue verpflichtet. Das Oberhaupt hatte die Aufgabe, die gesamte Familie zu schützen, die auch die Unfreien - die Knechte und Mägde - umfasste. Zu einer Sippe, die über die Kernfamilie hinausging, zählten alle Blutsverwandten. Kam es zu Streitigkeiten, besaßen die Sippen das Recht, ihre Angelegenheiten selbst zu regeln. Wurde ein Mitglied einer Sippe angegriffen, stand die ganze Sippe zusammen und verteidigte es. Gemeinsam mit anderen Sippen siedelte man in einer Dorfgemeinschaft und bildete so einen Stamm, der im Krieg als geschlossener Verband kämpfte.

Alle freien und kampffähigen Männer einer Stammesgemeinschaft bildeten zusammen das sogenannte Thing, das als Versammlung des Stammes das Oberhaupt wählte. Ebenso schnell konnte ein Oberhaupt auch wieder abgesetzt werden, wenn es seine Pflichten im Sinne der Gemeinschaft nicht erfüllte. Das Oberhaupt war eher ein Stammesführer als ein König oder Konsul, wie es bei Römern und Griechen zu dieser Zeit üblich war. Erst als sich Auseinandersetzungen mit den Römern häuften, begannen die Germanen, ihre Oberhäupter als Könige zu bezeichnen. Während des Thing, das meist im Freien an heiligen Stätten stattfand, galten strikte Regeln. Die Versammlung war den Göttern geweiht, eine Störung galt als Beleidigung der Götter und wurde von den Priestern hart bestraft. Jedes Mitglied des Rates hatte eine Stimme.

Die relativ kleinen Gruppen der Stämme verstanden sich jeweils als selbständige Einheit. Den Germanen gelang es deshalb nur selten, mehrere Stämme für ein gemeinsames Ziel zu vereinen. Genau dies hatten die Römer frühzeitig erkannt und machten es sich zunutze, indem sie Bündnisse mit verschiedenen Stämmen schlossen und die Germanen gegeneinander ausspielten. Untypisch für germanisches Verhalten war deshalb der Aufstand unter der Führung des Germanen Hermann aus dem Stamm der Cherusker im Jahre 9 nach Christus. Hermann, den die Römer Arminius nannten, war es gelungen, zerstrittene Stämme, die immer wieder untereinander Streitigkeiten austrugen, unter seiner Führung zu einen. Gemeinsam gelang es ihnen, sich erfolgreich gegen die Besatzungsmacht der Römer zur Wehr zu setzen. Die Herrschaft der Römer über die germanischen Stämme rechts des Rheins wurde so dauerhaft verhindert.""",
    },
}
